# -*- coding: utf-8 -*-
"""RAG .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hRIQP30pSiF063Ih7zlHmMLRsHEAYLW


!pip install -q sentence-transformers faiss-cpu numpy
"""
import os
import json
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
KNOWLEDGE_PATH = os.path.join(BASE_DIR, "data","knowledge.json")
with open(KNOWLEDGE_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

chunks = []

for landmark_id, landmark in data.items():
    landmark_name = landmark["name"]
    content = landmark["content"]


model = SentenceTransformer(
    "intfloat/multilingual-e5-base"
)

def get_chunks(landmark):
    chunks = []
    content = data[landmark]["content"]

    # =========================
    # 1. Regular sections
    # =========================
    sections = [
        "Overview",
        "History",
        "Tourism",
        "Nature",
        "Wildlife",
        "Activities",
        "Adventure",
        "Facts",
        "Fun Facts"
    ]

    for section in sections:
        items = content.get(section, [])

        if isinstance(items, list):
            for item in items:
                chunks.append({
                    "text": item,
                    "section": section,
                    "subsection": None
                })

    # =========================
    # 2. Landmarks_Details
    # =========================
    details_dict = content.get("Landmarks_Details", {})

    if isinstance(details_dict, dict):
        for landmark_name, details in details_dict.items():

            if isinstance(details, list) and details:

                # دمج جميع معلومات المعلم في Chunk واحد
                text = (
                    f"{landmark_name}: "
                    + " ".join(details)
                )

                chunks.append({
                    "text": text,
                    "section": "Landmarks_Details",
                    "subsection": landmark_name
                })

    return chunks

indices = {}

# المعالم الموجودة فعليًا في قاعدة المعرفة
landmarks = [
    "petra",
    "jerash",
    "ajloun_castle",
    "dead_sea",
    "wadi_rum",
    "um_al_jimal",
    "qasr_amra",
    "karak_castle",
    "al_maghtas",
    "Um_Qais",
    "wadi_mujib"
]

for landmark in landmarks:

    chunks = get_chunks(landmark)

    print(f"\n===== {landmark} =====")
    print("Number of chunks:", len(chunks))

    if not chunks:
        print(f"Skipping {landmark} due to no chunks.")
        continue

    # استخراج النصوص
    texts = [chunk["text"] for chunk in chunks]

    # التأكد أن النصوص صحيحة
    texts = [
        text for text in texts
        if isinstance(text, str) and text.strip()
    ]

    if not texts:
        print(f"Skipping {landmark} because there are no valid texts.")
        continue

    # Embeddings باستخدام E5
    embeddings = model.encode(
        ["passage: " + text for text in texts],
        normalize_embeddings=True,
        convert_to_numpy=True
    ).astype("float32")


    # إنشاء FAISS index
    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)

    # حفظ الـ index والـ chunks
    indices[landmark] = {
        "index": index,
        "chunks": chunks
    }


def retrieve_context(landmark, question, k=5):

    db = indices[landmark]
    index = db["index"]
    chunks = db["chunks"]

    # =========================
    # 1. Encode question
    # =========================
    query_embedding = model.encode(
        ["query: " + question],
        normalize_embeddings=True,
        convert_to_numpy=True
    ).astype("float32")

    # =========================
    # 2. Retrieve candidates
    # =========================
    search_k = len(chunks)
    scores, faiss_indices = index.search(
        query_embedding,
        search_k
    )

    candidates = []

    for score, idx in zip(scores[0], faiss_indices[0]):

        if idx < 0:
            continue

        chunk = chunks[idx]

        candidates.append({
            "text": chunk["text"],
            "section": chunk["section"],
            "subsection": chunk.get("subsection"),
            "score": float(score)
        })

    # =========================
    # 3. Normalize question
    # =========================
    q = question.lower().strip()

    # =========================
    # 4. Intent keywords
    # =========================

    route_keywords = [
        # Arabic
        "مسار",
        "مسارات",
        "ممر",
        "ممرات",
        "مغامرة",
        "المسارات المائية",
        "الممرات المائية",

        # English
        "trail",
        "trails",
        "path",
        "paths",
        "route",
        "routes",
        "water trail",
        "water trails",
        "adventure"
    ]

    wildlife_keywords = [
        # Arabic
        "حيوان",
        "حيوانات",
        "طيور",
        "حياة برية",
        "الوعل",
        "كاراكال",

        # English
        "animal",
        "animals",
        "wildlife",
        "birds",
        "mammals",
        "caracal",
        "ibex"
    ]

    history_keywords = [
        # Arabic
        "تاريخ",
        "تاريخيًا",
        "تاريخيا",
        "قديم",
        "العصور",
        "موآب",
        "عمون",
        "الرومان",

        # English
        "history",
        "historical",
        "historically",
        "ancient",
        "roman",
        "moab",
        "ammon"
    ]

    location_keywords = [
        # Arabic
        "أين يقع",
        "أين توجد",
        "موقع",
        "يقع",

        # English
        "where",
        "located",
        "location",
        "situated"
    ]

    tourism_keywords = [
        # Arabic
        "زيارة",
        "يزور",
        "متى",
        "أفضل وقت",
        "وقت الزيارة",
        "موسم",

        # English
        "visit",
        "visiting",
        "when",
        "best time",
        "season",
        "seasonal"
    ]

    # =========================
    # 5. Detect intent
    # =========================

    is_route_question = any(
        word in q for word in route_keywords
    )

    is_wildlife_question = any(
        word in q for word in wildlife_keywords
    )

    is_history_question = any(
        word in q for word in history_keywords
    )

    is_location_question = any(
        word in q for word in location_keywords
    )

    is_tourism_question = any(
        word in q for word in tourism_keywords
    )

    # =========================
    # 6. Route question
    # =========================

    if is_route_question:

        # Actual trail/path names in Wadi Mujib
        trail_names = [
            "مسار البدن",
            "مسار الهيدان",
            "ممر الملاقي",
            "ممر الشلال",
            "ممر السيق"
        ]

        route_candidates = []

        for candidate in candidates:

            subsection = candidate.get("subsection")

            if subsection in trail_names:
                route_candidates.append(candidate)

        # If enough actual trails were found,
        # use only those results.
        if len(route_candidates) >= k:

            route_candidates.sort(
                key=lambda x: x["score"],
                reverse=True
            )

            return route_candidates[:k]

        # Otherwise return all detected trail candidates
        if route_candidates:

            route_candidates.sort(
                key=lambda x: x["score"],
                reverse=True
            )

            return route_candidates[:k]

        # Fallback
        candidates.sort(
            key=lambda x: x["score"],
            reverse=True
        )

        return candidates[:k]

    # =========================
    # 7. Wildlife question
    # =========================

    elif is_wildlife_question:

        candidates.sort(
            key=lambda x: (
                x["section"] in ["Wildlife", "Nature"],
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 8. History question
    # =========================

    elif is_history_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "History",
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 9. Location question
    # =========================

    elif is_location_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Overview",
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 10. Tourism question
    # =========================

    elif is_tourism_question:

        candidates.sort(
            key=lambda x: (
                x["section"] in [
                    "Tourism",
                    "Activities",
                    "Adventure"
                ],
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 11. General question
    # =========================

    else:

        candidates.sort(
            key=lambda x: x["score"],
            reverse=True
        )

    return candidates[:k]

results = retrieve_context(
    "wadi_mujib",
    "ما هي أشهر المسارات في وادي الموجب؟",
    k=5
)

for i, result in enumerate(results, 1):
    print(f"\n{i}. Score: {result['score']:.4f}")
    print("Section:", result["section"])
    print("Subsection:", result["subsection"])
    print("Text:", result["text"])

tests = [
    "ما هي أشهر المسارات في وادي الموجب؟",
    "ما الحيوانات التي تعيش في محمية الموجب؟",
    "متى يمكن زيارة المسارات المائية؟",
    "ما أهمية وادي الموجب تاريخيًا؟",
    "أين يقع وادي الموجب؟"
]

for question in tests:

    print("\n" + "=" * 70)
    print("QUESTION:", question)

    results = retrieve_context(
        "wadi_mujib",
        question,
        k=5
    )

    for i, result in enumerate(results, 1):
        print(
            f"{i}. [{result['score']:.4f}] "
            f"{result['section']} → "
            f"{result.get('subsection')}"
        )
        print(result["text"])

tests_en = [
    "What are the most famous trails in Wadi Mujib?",
    "What animals live in Mujib Nature Reserve?",
    "When can I visit the water trails?",
    "What is the historical importance of Wadi Mujib?",
    "Where is Wadi Mujib located?"
]

for question in tests_en:

    print("\n" + "=" * 70)
    print("QUESTION:", question)

    results = retrieve_context(
        "wadi_mujib",
        question,
        k=5
    )

    for i, result in enumerate(results, 1):
        print(
            f"{i}. [{result['score']:.4f}] "
            f"{result['section']} → "
            f"{result.get('subsection')}"
        )
        print(result["text"])