# -*- coding: utf-8 -*-
"""RAG .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hRIQP30pSiF063Ih7zlHmMLRsHEAYLW


!pip install -q sentence-transformers faiss-cpu numpy
"""
# -*- coding: utf-8 -*-

import os
import pickle
import faiss

from sentence_transformers import SentenceTransformer


# ============================================================
# 1. Paths
# ============================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

RAG_DIR = os.path.join(
    BASE_DIR,
    "rag_data"
)
KNOWLEDGE_PATH = os.path.join(
    RAG_DIR,
    "knowledge.json"
)

# ============================================================
# 2. Landmarks
# ============================================================

landmarks = [
    "petra",
    "jerash",
    "ajloun_castle",
    "dead_sea",
    "wadi_rum",
    "um_al_jimal",
    "qasr_amra",
    "karak_castle",
    "al_maghtas",
    "umm_qays",
    "wadi_mujib"
]


# ============================================================
# 3. Landmark name mapping
# ============================================================

LANDMARK_MAP = {
    "Petra": "petra",
    "Jerash": "jerash",
    "Ajloun_Castle": "ajloun_castle",
    "wadi_Rum": "wadi_rum",
    "Dead_Sea": "dead_sea",
    "Um_AL_Jimal": "um_al_jimal",
    "Qasr_Amra": "qasr_amra",
    "Karak_Castle": "karak_castle",
    "Al_Maghtas": "al_maghtas",
    "Wadi_Mujib": "wadi_mujib",
    "Um_Qais": "umm_qays"
}


# ============================================================
# 4. Load embedding model
# ============================================================

model = SentenceTransformer(
    "intfloat/multilingual-e5-base",
    device="cpu"
)


# ============================================================
# 5. Load FAISS indexes and chunks
# ============================================================

indices = {}

for landmark in landmarks:

    index_path = os.path.join(
        RAG_DIR,
        f"{landmark}.index"
    )

    chunks_path = os.path.join(
        RAG_DIR,
        f"{landmark}.pkl"
    )

    if not os.path.exists(index_path):
        print(f"Missing index: {index_path}")
        continue

    if not os.path.exists(chunks_path):
        print(f"Missing chunks: {chunks_path}")
        continue

    index = faiss.read_index(index_path)

    with open(chunks_path, "rb") as f:
        chunks = pickle.load(f)

    indices[landmark] = {
        "index": index,
        "chunks": chunks
    }

# ============================================================
# 6. Retrieve context
# ============================================================
def retrieve_context(landmark, question, k=10):


    rag_landmark = LANDMARK_MAP.get(
        landmark,
        landmark
    )

    if rag_landmark not in indices:
        print(
            f"RAG index not found for: {rag_landmark}"
        )
        return []

    db = indices[rag_landmark]

    index = db["index"]
    chunks = db["chunks"]

    # ========================================================
    # 1. Encode question
    # ========================================================

    query_embedding = model.encode(
        ["query: " + question],
        normalize_embeddings=True,
        convert_to_numpy=True
    ).astype("float32")

    # ========================================================
    # 2. Retrieve candidates
    # ========================================================

    search_k = len(chunks)

    scores, faiss_indices = index.search(
        query_embedding,
        search_k
    )

    candidates = []

    for score, idx in zip(
        scores[0],
        faiss_indices[0]
    ):

        if idx < 0:
            continue

        chunk = chunks[idx]

        candidates.append({
            "text": chunk["text"],
            "section": chunk["section"],
            "subsection": chunk.get("subsection"),
            "score": float(score)
        })

    # ========================================================
    # 3. Normalize question
    # ========================================================

    q = question.lower().strip()

    # ========================================================
    # 4. Intent keywords
    # ========================================================

    route_keywords = [
        "مسار",
        "مسارات",
        "ممر",
        "ممرات",
        "مغامرة",
        "المسارات المائية",
        "الممرات المائية",
        "trail",
        "trails",
        "path",
        "paths",
        "route",
        "routes",
        "water trail",
        "water trails",
        "adventure"
    ]

    wildlife_keywords = [
        "حيوان",
        "حيوانات",
        "طيور",
        "حياة برية",
        "الوعل",
        "كاراكال",
        "animal",
        "animals",
        "wildlife",
        "birds",
        "mammals",
        "caracal",
        "ibex"
    ]

    history_keywords = [
        "تاريخ",
        "تاريخيًا",
        "تاريخيا",
        "قديم",
        "العصور",
        "موآب",
        "عمون",
        "الرومان",
        "بنى",
        "بنيت",
        "بناء",
        "بُني",
        "بُنيت",
        "أسس",
        "أسست",
        "تأسس",
        "تأسست",
        "أنشأ",
        "أنشئت",
        "قصة",
        "قصتها",
        "history",
        "historical",
        "historically",
        "ancient",
        "roman",
        "moab",
        "ammon",
        "built",
        "founded",
        "established",
        "constructed",
        "story"
    ]

    facts_keywords = [
        "حقائق",
        "حقيقة",
        "معلومات",
        "مهم",
        "مهمة",
        "الأشياء المهمة",
        "facts",
        "fact",
        "information"
    ]

    landmarks_keywords = [
        "معالم",
        "معلم",
        "أماكن",
        "مكان",
        "الأماكن",
        "landmarks",
        "landmark",
        "places",
        "place"
    ]

    entrance_keywords = [
        "مدخل",
        "المدخل",
        "مدخلها",
        "entrance"
    ]

    location_keywords = [
        "أين يقع",
        "أين تقع",
        "وين يقع",
        "وين تقع",
        "أين توجد",
        "وين توجد",
        "وين موجودة",
        "موقع",
        "where",
        "located",
        "location",
        "situated"
    ]

    tourism_keywords = [
        "زيارة",
        "يزور",
        "أفضل وقت",
        "وقت الزيارة",
        "موسم",
        "أعمل",
        "اعمل",
        "أقدر أعمل",
        "اقدر اعمل",
        "أنشطة",
        "نشاطات",
        "نشاط",
        "فعاليات",
        "أزور",
        "ازور",
        "أستكشف",
        "استكشف",
        "الدير",
        "visit",
        "visiting",
        "best time",
        "season",
        "seasonal",
        "things to do",
        "activities",
        "activity"
    ]

    opening_hours_keywords = [
        "متى تفتح",
        "متى يفتح",
        "متى تغلق",
        "متى يغلق",
        "وقت الفتح",
        "وقت الإغلاق",
        "أوقات الدوام",
        "ساعات العمل",
        "ساعات الدوام",
        "مواعيد الدخول",
        "متى يمكن الدخول",
        "opening hours",
        "opening time",
        "closing time",
        "when does it open",
        "when does it close",
        "what time does it open",
        "what time does it close"
    ]

    visitor_statistics_keywords = [
        "زوار",
        "الزوار",
        "سياح",
        "السياح",
        "عدد الزوار",
        "عدد السياح",
        "كم زائر",
        "كم سائح",
        "إحصائيات الزوار",
        "إحصائيات السياح",
        "إحصاءات الزوار",
        "إحصاءات السياح",
        "عدد الزائرين",
        "عدد السائحين",
        "visitor",
        "visitors",
        "tourist",
        "tourists",
        "visitor statistics",
        "tourism statistics",
        "number of visitors",
        "number of tourists"
    ]

    # ========================================================
    # 5. Detect intent
    # ========================================================

    is_route_question = any(
        word in q for word in route_keywords
    )

    is_wildlife_question = any(
        word in q for word in wildlife_keywords
    )

    is_history_question = any(
        word in q for word in history_keywords
    )

    is_facts_question = any(
        word in q for word in facts_keywords
    )

    is_landmarks_question = any(
        word in q for word in landmarks_keywords
    )

    is_entrance_question = any(
        word in q for word in entrance_keywords
    )

    is_location_question = any(
        word in q for word in location_keywords
    )

    is_tourism_question = any(
        word in q for word in tourism_keywords
    )

    is_opening_hours_question = any(
        word in q for word in opening_hours_keywords
    )

    is_visitor_statistics_question = any(
        word in q for word in visitor_statistics_keywords
    )

    # ========================================================
    # 6. Rank candidates by detected intent
    # ========================================================

    if is_route_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Landmarks",
                x["score"]
            ),
            reverse=True
        )

    elif is_wildlife_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Facts",
                x["score"]
            ),
            reverse=True
        )

    elif is_history_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "History",
                x["score"]
            ),
            reverse=True
        )

    elif is_entrance_question:

        candidates.sort(
            key=lambda x: (
                x.get("subsection") == "السيق",
                x["section"] == "Landmarks_Details",
                x["score"]
            ),
            reverse=True
        )

    elif is_facts_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Facts",
                x["score"]
            ),
            reverse=True
        )

    elif is_landmarks_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Landmarks",
                x["score"]
            ),
            reverse=True
        )

    elif is_location_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Overview",
                x["score"]
            ),
            reverse=True
        )

    elif is_opening_hours_question:

        candidates.sort(
            key=lambda x: (
                x.get("subsection") == "Opening_Hours",
                x["section"] == "Practical_Info",
                x["score"]
            ),
            reverse=True
        )

    elif is_visitor_statistics_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Practical_Info",
                x.get("subsection") == "Visitor_Statistics",
                x["score"]
            ),
            reverse=True
        )

    elif is_tourism_question:

        candidates.sort(
            key=lambda x: (
                x["section"] in [
                    "Tourism",
                    "Activities",
                    "Adventure"
                ],
                x["score"]
            ),
            reverse=True
        )

    else:

        candidates.sort(
            key=lambda x: x["score"],
            reverse=True
        )

    
    

    # ========================================================
    # 7. Return context
    # ========================================================

    return candidates[:k]
