# -*- coding: utf-8 -*-
"""RAG .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hRIQP30pSiF063Ih7zlHmMLRsHEAYLW


!pip install -q sentence-transformers faiss-cpu numpy
"""
import os
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss
import pickle

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RAG_DIR = os.path.join(BASE_DIR, "rag_data")

indices = {}

landmarks = [
    "petra",
    "jerash",
    "ajloun_castle",
    "dead_sea",
    "wadi_rum",
    "um_al_jimal",
    "qasr_amra",
    "karak_castle",
    "al_maghtas",
    "umm_qays",
    "wadi_mujib"
]


model = SentenceTransformer(
    "intfloat/multilingual-e5-base",
        device="cpu"

)

for landmark in landmarks:

    index_path = os.path.join(RAG_DIR, f"{landmark}.index")
    chunks_path = os.path.join(RAG_DIR, f"{landmark}.pkl")

    index = faiss.read_index(index_path)
    with open(chunks_path, "rb") as f:
        chunks = pickle.load(f)
    indices[landmark] = {
        "index": index,
        "chunks": chunks
    }

    LANDMARK_MAP = {
    "Petra": "petra",
    "Jerash": "jerash",
    "Ajloun_Castle": "ajloun_castle",
    "wadi_Rum": "wadi_rum",
    "Dead_Sea": "dead_sea",
    "Um_AL_Jimal": "um_al_jimal",
    "Qasr_Amra": "qasr_amra",
    "Karak_Castle": "karak_castle",
    "Al_Maghtas": "al_maghtas",
    "Wadi_Mujib": "wadi_mujib",
    "Um_Qais": "umm_qays"
}

def retrieve_context(landmark, question, k=10):

    rag_landmark = LANDMARK_MAP.get(landmark, landmark)

    db = indices[rag_landmark]
    index = db["index"]
    chunks = db["chunks"]

    # =========================
    # 1. Encode question
    # =========================
    query_embedding = model.encode(
        ["query: " + question],
        normalize_embeddings=True,
        convert_to_numpy=True
    ).astype("float32")

    # =========================
    # 2. Retrieve candidates
    # =========================
    search_k = len(chunks)

    scores, faiss_indices = index.search(
        query_embedding,
        search_k
    )

    candidates = []

    for score, idx in zip(scores[0], faiss_indices[0]):

        if idx < 0:
            continue

        chunk = chunks[idx]

        candidates.append({
            "text": chunk["text"],
            "section": chunk["section"],
            "subsection": chunk.get("subsection"),
            "score": float(score)
        })

    # =========================
    # 3. Normalize question
    # =========================
    q = question.lower().strip()

    # =========================
    # 4. Intent keywords
    # =========================

    route_keywords = [
        # Arabic
        "مسار",
        "مسارات",
        "ممر",
        "ممرات",
        "مغامرة",
        "المسارات المائية",
        "الممرات المائية",

        # English
        "trail",
        "trails",
        "path",
        "paths",
        "route",
        "routes",
        "water trail",
        "water trails",
        "adventure"
    ]

    wildlife_keywords = [
        # Arabic
        "حيوان",
        "حيوانات",
        "طيور",
        "حياة برية",
        "الوعل",
        "كاراكال",

        # English
        "animal",
        "animals",
        "wildlife",
        "birds",
        "mammals",
        "caracal",
        "ibex"
    ]

    history_keywords = [
        # Arabic
        "تاريخ",
        "تاريخيًا",
        "تاريخيا",
        "قديم",
        "العصور",
        "موآب",
        "عمون",
        "الرومان",
        "بنى",
        "بنيت",
        "بناء",
        "بُني",
        "بُنيت",
        "أسس",
        "أسست",
        "تأسس",
        "تأسست",
        "أنشأ",
        "أنشئت",
        "قصة",
        "قصتها",

        # English
        "history",
        "historical",
        "historically",
        "ancient",
        "roman",
        "moab",
        "ammon",
        "built",
        "founded",
        "established",
        "constructed",
        "story"
    ]

    facts_keywords = [
        # Arabic
        "حقائق",
        "حقيقة",
        "معلومات",
        "مهم",
        "مهمة",
        "الأشياء المهمة",

        # English
        "facts",
        "fact",
        "information"
    ]

    landmarks_keywords = [
        # Arabic
        "معالم",
        "معلم",
        "أماكن",
        "مكان",
        "الأماكن",

        # English
        "landmarks",
        "landmark",
        "places",
        "place"
    ]

    entrance_keywords = [
        # Arabic
        "مدخل",
        "المدخل",
        "مدخلها",

        # English
        "entrance"
    ]

    location_keywords = [
        # Arabic
        "أين يقع",
        "أين تقع",
        "وين يقع",
        "وين تقع",
        "أين توجد",
        "وين توجد",
        "وين موجودة",
        "موقع",
        "يقع",
        "تقع",

        # English
        "where",
        "located",
        "location",
        "situated"
    ]

    tourism_keywords = [
        # Arabic
        "زيارة",
        "يزور",
        "أفضل وقت",
        "وقت الزيارة",
        "موسم",
        "أعمل",
        "اعمل",
        "أقدر أعمل",
        "اقدر اعمل",
        "أنشطة",
        "نشاطات",
        "نشاط",
        "فعاليات",
        "أزور",
        "ازور",
        "أستكشف",
        "استكشف",
        "الدير",

        # English
        "visit",
        "visiting",
        "best time",
        "season",
        "seasonal",
        "things to do",
        "activities",
        "activity"
    ]


    # =========================
    # 5. Detect intent
    # =========================

    is_route_question = any(
        word in q for word in route_keywords
    )

    is_wildlife_question = any(
        word in q for word in wildlife_keywords
    )

    is_history_question = any(
        word in q for word in history_keywords
    )

    is_facts_question = any(
        word in q for word in facts_keywords
    )

    is_landmarks_question = any(
        word in q for word in landmarks_keywords
    )

    is_entrance_question = any(
        word in q for word in entrance_keywords
    )

    is_location_question = any(
        word in q for word in location_keywords
    )

    is_tourism_question = any(
        word in q for word in tourism_keywords
    )

    # =========================
    # 6. Route question
    # =========================

    if is_route_question:

        trail_names = [
            "مسار البدن",
            "مسار الهيدان",
            "ممر الملاقي",
            "ممر الشلال",
            "ممر السيق"
        ]

        route_candidates = []

        for candidate in candidates:

            subsection = candidate.get("subsection")

            if subsection in trail_names:
                route_candidates.append(candidate)

        if len(route_candidates) >= k:

            route_candidates.sort(
                key=lambda x: x["score"],
                reverse=True
            )

            return route_candidates[:k]

        if route_candidates:

            route_candidates.sort(
                key=lambda x: x["score"],
                reverse=True
            )

            return route_candidates[:k]

        candidates.sort(
            key=lambda x: x["score"],
            reverse=True
        )

        return candidates[:k]

    # =========================
    # 7. Wildlife question
    # =========================

    elif is_wildlife_question:

        candidates.sort(
            key=lambda x: (
                x["section"] in ["Wildlife", "Nature"],
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 8. History question
    # =========================

    elif is_history_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "History",
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 9. Entrance question
    # =========================

    elif is_entrance_question:

        candidates.sort(
            key=lambda x: (
                x.get("subsection") == "السيق",
                x["section"] == "Landmarks_Details",
                x["score"]
            ),
            reverse=True
        )
    # =========================
    # 10. Facts question
    # =========================

    elif is_facts_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Facts",
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 11. Landmarks question
    # =========================

    elif is_landmarks_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Landmarks",
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 12. Location question
    # =========================

    elif is_location_question:

        candidates.sort(
            key=lambda x: (
                x["section"] == "Overview",
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 13. Tourism question
    # =========================

    elif is_tourism_question:

        candidates.sort(
            key=lambda x: (
                x["section"] in [
                    "Tourism",
                    "Activities",
                    "Adventure"
                ],
                x["score"]
            ),
            reverse=True
        )

    # =========================
    # 14. General question
    # =========================

    else:

        candidates.sort(
            key=lambda x: x["score"],
            reverse=True
        )

    # =========================
    # 15. Return top results
    # =========================


    return candidates[:k]